/* Parameters */ 
// All lenghts are in mm

$fn = 50;

WHEEL_MAX_RAD = 60;
INNER_RIM_RAD = 50;


TENNIS_BALL_CURAVTURE_RAD = 33;

CURVE_FACETS = 100;

BALL_CURAVTURE_RAD = 60;

X_DIM =WHEEL_MAX_RAD - INNER_RIM_RAD;
Y_DIM = 2*TENNIS_BALL_CURAVTURE_RAD - 15;

FILLER_HEIGHT = 10;

BOLT_COUNT = 6;
BOLT_SPREAD = 35;
BOLT_DIM = 5.4;
CENTER_DIM = 6.4;

MAKE_HALF = true;

/* Skirt parameters */

BALL_TRAVEL_SPACE = 50;
SKIRT_THICKNESS = 10;
SKIRT_RADIUS_OFFSET = 60;
RAIL_WIDTH = 8;
RAIL_HEIGHT = 5;
DROP_TANGENT_LENGTH = 70;

/* Assembly Params */


SPINE_HEIGHT = 400;
SPINE_WIDTH = 70;
SPINE_THICKNESS = 30;

WHEEL_SPINE_GAP = 10;

BOTTOM_WHEEL_GAP_TO_FLOOR = 20;

GAP_BETWEEN_SERVER_WHEELS = 50;